# Site settings
title: Codestone
email: info@codestone.nl

#Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
description: "Codestone - Android App Development - Community Building"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 99CC00 #80B3FF
  secondary: 77AA00 #FD6E8A
  secondary-dark: 669900 #A2122F
  
# Footer settings
footer:
  copyright: Codestone
  location: Contact
  social: Around the Web
  credits: Company Info

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google-plus
    url: http://google.com/+JohanPelgrim
  - title: twitter
    url: http://twitter.com/jowipe
  - title: linkedin
    url: https://www.linkedin.com/in/johanpelgrim
  - title: group
    url: http://www.dutchaug.org
  - title: github
    url: http://github.com/jpelgrim

# Postal address (add as many lines as necessary)
address:
  - line: +31(0)627189651
  - line: Noordvaarder 39
  - line: 2134 XZ, Hoofddorp
  - line: The Netherlands

# Credits content
credits: 'e-mail: info@codestone.nl<br/>KvK: 34381941<br/>BTW nr: NL1835.15.055.B01<br/><a href="/algemene-voorwaarden-codestone.pdf" class="btn btn-lg btn-outline"><i class="fa fa-download"></i> Terms &amp; Conditions (in Dutch)</a>'

# Build settings
markdown: kramdown
permalink: pretty
